name: CSS Linting

on: [push]

jobs:
  stylelint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or whatever version you prefer

    - name: Install Dependencies
      run: npm install

    - name: Run Stylelint
      run: npx stylelint "**/*.css"
